### PR TITLE
修复ChartAdivsor测试

### PR DESCRIPTION
**Pull request by Cuiyansong**
### PR includes

- [ ] fixed #0
- [x] add / modify test cases
- [ ] documents, demos

### CODE REVIEW

**Comment by Cuiyansong** [comment]
Sorry about to missing commit #402  which fixed test issue

**Review by neoddish — CHANGES_REQUESTED** [review]
thx for your contribution! I'd love to rebase merge your commits but there are two commits about CA test should be rebased into one. Would you modify them, plz?

**Comment by Cuiyansong** [comment]
> thx for your contribution! I'd love to rebase merge your commits but there are two commits about CA test should be rebased into one. Would you modify them, plz?

Sure, which two? This pr with two commits, one is fix tests, an the other one is improve documents, you mean this two?

**Comment by neoddish** [comment]
> > thx for your contribution! I'd love to rebase merge your commits but there are two commits about CA test should be rebased into one. Would you modify them, plz?
> 
> Sure, which two? This pr with two commits, one is fix tests, and the other one is improve documents, you mean this two?

this pr contains [3 commits](https://github.com/antvis/AVA/pull/412/commits), and these two commits solve the same problem on the same file, the latter being a modification of the former. They should be rebased into one:

* [test(chart-advisor): fix tests after ckb increase knowledge](https://github.com/antvis/AVA/pull/412/commits/bfe104e59cc36fbea304fb08813f7c38ad30d195)
* [test(chart-advisor): the original cbk count should be a relative numb…](https://github.com/antvis/AVA/pull/412/commits/7d1a22919e86e5429c2487aaf02ebed60a596624)

the doc one is fine. However, `docs` would be more accurate than `chore` in terms of its semantic type.

I suggest that this PR contains two commits as follows:
* test(ca/advisor): fix test cases about custom ckb
* docs(ca/advisor): opt jsdoc of dataToAdvices

thx!

**Comment by Cuiyansong** [comment]
> > > thx for your contribution! I'd love to rebase merge your commits but there are two commits about CA test should be rebased into one. Would you modify them, plz?
> > 
> > 
> > Sure, which two? This pr with two commits, one is fix tests, and the other one is improve documents, you mean this two?
> 
> this pr contains [3 commits](https://github.com/antvis/AVA/pull/412/commits), and these two commits solve the same problem on the same file, the latter being a modification of the former. They should be rebased into one:
> 
> * [test(chart-advisor): fix tests after ckb increase knowledge](https://github.com/antvis/AVA/pull/412/commits/bfe104e59cc36fbea304fb08813f7c38ad30d195)
> * [test(chart-advisor): the original cbk count should be a relative numb…](https://github.com/antvis/AVA/pull/412/commits/7d1a22919e86e5429c2487aaf02ebed60a596624)
> 
> the doc one is fine. However, `docs` would be more accurate than `chore` in terms of its semantic type.
> 
> I suggest that this PR contains two commits as follows:
> 
> * test(ca/advisor): fix test cases about custom ckb
> * docs(ca/advisor): opt jsdoc of dataToAdvices
> 
> thx!

Sorry to forget it, it is 3 commits indeed :). I will push a new pr now. Thanks

**Comment by neoddish** [comment]
new PR: #414

**Pull request closed without merging**
