### PR TITLE
Refactor: chart advisor

### PR DESCRIPTION
**Pull request by BBSQQ**
* Group autoChart in a folder
* define DataProps clearly to make pipeline start with dataPropsToAdvice easily

### CODE REVIEW

**Review by neoddish — APPROVED** [review]
LGTM

**Comment by neoddish** [comment]
Conflicts...

**Comment by BBSQQ** [comment]
> Conflicts...

already solved, pls re again

**Review by neoddish — APPROVED** [review]
LGTM

**Pull request merged**
