### PR TITLE
feat(ckb): add definitions of wordcloud, nested pie chart, candlestick chart

### PR DESCRIPTION
**Pull request by GuangMingYouBei**
### PR includes

- feat(ckb): add definitions of wordcloud, nested pie chart, candlestick chart

### CODE REVIEW

**Comment by neoddish** [comment]
would u add i18n as well, plz?

**Comment by GuangMingYouBei** [comment]
> 



> would u add i18n as well, plz?

Added

**Review by neoddish — APPROVED** [review]
LGTM

**Pull request merged**
